spring.application.name=tutoria1

spring.datasource.url=jdbc:mysql://localhost:3330/tutoria1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true